In [ ]:
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [ ]:
data = pd.read_csv("reviews_dataset.csv", sep=',')

data.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams

In [ ]:
# Define functions for semtiment analysis

def get_sentiment(text):
    sentiment = analyzer.polarity_scores(text)
    return sentiment

# Apply VADER to the 'reviews.text' column and store the results in a new column 'sentiment'

data['sentiment'] = data['reviews.text'].apply(get_sentiment)

In [ ]:
# Extract compound sentiment scores

data['compound'] = data['sentiment'].apply(lambda x: x['compound'])

data['sentiment']

0       {'neg': 0.038, 'neu': 0.793, 'pos': 0.169, 'co...
1       {'neg': 0.041, 'neu': 0.812, 'pos': 0.147, 'co...
2       {'neg': 0.181, 'neu': 0.596, 'pos': 0.223, 'co...
3       {'neg': 0.03, 'neu': 0.865, 'pos': 0.105, 'com...
4       {'neg': 0.089, 'neu': 0.715, 'pos': 0.195, 'co...
                              ...
1592    {'neg': 0.163, 'neu': 0.761, 'pos': 0.076, 'co...
1593    {'neg': 0.12, 'neu': 0.851, 'pos': 0.029, 'com...
1594    {'neg': 0.198, 'neu': 0.802, 'pos': 0.0, 'comp...
1595    {'neg': 0.109, 'neu': 0.66, 'pos': 0.23, 'comp...
1596    {'neg': 0.121, 'neu': 0.863, 'pos': 0.017, 'co...
Name: sentiment, Length: 1597, dtype: object

In [ ]:
# Define function for sentiment classification of reviews

def classify_sentiment(compound_score):
    if compound_score > 0.4:
        return "positive"
    elif compound_score < 0.1:
        return "negative"
    else:
        return "neutral"

data['sentiment_category'] = data['compound'].apply(classify_sentiment)
data.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight,sentiment,compound,sentiment_category
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams,"{'neg': 0.038, 'neu': 0.793, 'pos': 0.169, 'co...",0.9804,positive
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams,"{'neg': 0.041, 'neu': 0.812, 'pos': 0.147, 'co...",0.9874,positive
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams,"{'neg': 0.181, 'neu': 0.596, 'pos': 0.223, 'co...",0.4364,positive
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams,"{'neg': 0.03, 'neu': 0.865, 'pos': 0.105, 'com...",0.9743,positive
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams,"{'neg': 0.089, 'neu': 0.715, 'pos': 0.195, 'co...",0.9930,positive

In [ ]:
# Save the DataFrame to a CSV file
data.to_csv('reviews_analysed.csv', index=False)